@startuml use-case
left to right direction

:User: as user
:Script: as scp

rectangle browser { 
    user -- (1. 情報の入力)
    user -- (2. フォームの送信)
    scp --(3. テキストの作成) 
    user -- (4. テキストの取得) 
}

' user -- info
' user -- get
' scp -- crt

@enduml